### ISSUE TITLE
service 支持自定义 annotations

### ISSUE THREAD

**Issue by jugggao** [ossrs/srs-helm#3]
如题

**Comment by jugggao** [comment]
example:

```yaml
spec:
  {{- if (or (eq .Values.service.type "ClusterIP" "") (empty .Values.service.type)) }}
  type: {{ .Values.service.type }}
  {{- if not (empty .Values.service.clusterIP) }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- else if eq .Values.service.type "LoadBalancer" }}
  type: {{ .Values.service.type }}
  loadBalancerIP: {{ default "" .Values.service.loadBalancerIP }}
  {{- else }}
  type: {{ .Values.service.type }}
  {{- end }}
```

**Comment by jugggao** [comment]
Ingress 也需要做一些更改才能在 SRS 播放器中正常的播放 WHEP。

ingress.yaml:

```yaml
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $.svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $.svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
```

values-custom.yaml:

```yaml
ingress:
  enabled: true
  className: "nginx-common"
  annotations: {}
  hosts:
  - host: nonprod-srs.example.cn
    paths:
    - path: /
      pathType: ImplementationSpecific
      svcPort: 8080
    - path: /api
      pathType: ImplementationSpecific
      svcPort: 1985
    - path: /rtc
      pathType: ImplementationSpecific
      svcPort: 1985
  tls:
  - hosts:
    - nonprod-srs.example.cn
    secretName: example-tls
```
